server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:  # 设置要绑定的rabbitmq的服务信息
        defaultRabbit:  # 设置消息服务具体设置的的名称，用于和binding整合
          type: rabbit  # 消息中间件类型
          environment:  # 设置rabbitmq相关信息
            spring:
              rabbitmq:
                host: 192.168.121.100
                port: 5672
                username: guest
                passowrd: guest
      bindings: # 设置服务的整合
        output: # channel的名称
          destination: studyExchange  # 设置交换机的名称
          content-type: application/json  # 设置消息的类型为json，文本类型为“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: send-8801.com  # 在信息列表中显示主机名称
    prefer-ip-address: true # 访问的路径变为ip地址
