server:
  port: 86

spring:
  application:
    name: cloud-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.100:8848
    sentinel:
      transport:
        dashboard: 192.168.121.100:8080
        port: 8719

feign:
  sentinel:
    enabled: true # 开启sentinel对feign的支持