server:
  port: 9004

spring:
  application:
    name: cloud-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.100:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'  # 开启web监控端点