server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group  # 指定seata事务组的名称（需要与seata/conf/file.conf中的设置对应）
    nacos:
      discovery:
        server-addr: 192.168.121.100:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.121.100:3306/seata_order
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info # 设置seata的log日志级别

mybatis:
  mapper-locations: classpath:mapper/*.xml
